---
driver:
  name: dokken
  use_sudo: false
  privileged: true
  chef_version: '14.14.29'

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: <%= !ENV['CI'] %>
  data_bags_path: test/fixtures/data_bags

verifier:
  name: inspec

platforms:
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN useradd -m -s /bin/bash ubuntu

suites:
- name: default
  run_list:
    - recipe[apt::default]
    - recipe[vsftpd::default]
  attributes:
    vsftpd:
      config:
        listen_address: 127.0.0.1
      allowed:
        - vagrant
